### ISSUE TITLE
Appearances

### ISSUE THREAD

**Issue by AzF01** [sortitoutsi/Football-transfer-scripts#2]
Interested if it would be possible to adapt the package so one can pull appearances in Champions League and international appearances for a select group of players (e.g. all Premier league players)

**Comment by krissmed** [comment]
That is not in the scope of the project, at least not yet. I will look into it if there is sufficient interest, but not likely at the moment. 

That said, any contributions would be appreciated, so feel free to do so yourself and make a pull request.
